### ISSUE TITLE
TypeError: Cannot read property 'ctime' of undefined

### ISSUE THREAD

**Issue by ItsNickBarry** [wighawag/buidler-preprocessor#1]
This error appears when simply calling `usePlugin('buidler-preprocessor')` (buidler version 1.4.7):

```
TypeError: Cannot read property 'ctime' of undefined
```

**Comment by wighawag** [comment]
Hi @ItsNickBarry thanks for reporting. It seems I am using fs.stat wrongly. not sure how it worked for me ?
I ll fix that

**Comment by ItsNickBarry** [comment]
I think it ran successfully a few times for me, but then it stopped working.

**Comment by wighawag** [comment]
I made an attempt to fix it. I use the `fs.statSync` version now
my tests continue to pass
