### ISSUE TITLE
Pass file path to eachLine function

### ISSUE THREAD

**Issue by ItsNickBarry** [wighawag/buidler-preprocessor#2]
I would like to import solidity files within the same package by referencing the name of the package, rather than relatively.  For example, developing an `ERC20` in package `token`:

```solidity
// ERC20.sol

// not like this
import './IERC20.sol';

// like this
import 'token/contracts/IERC20.sol':
```

This requires the path of the file being processed to be available in the `eachLine` function.  Do you think this feature would fit into the plugin structure?

**Comment by wighawag** [comment]
Yes, sounds like a simple addition.
the line processor function could be like `(line: string, file: {path:string}) => string`

**Comment by wighawag** [comment]
in 0.0.3 I made line preprocessor this type : 
`export type LinePreprocessor = (line: string, fileInfo: {absolutePath: string}) => string;`

let me know if you think a relative path would be simpler or any other feedback

**Comment by ItsNickBarry** [comment]
Seems to be working, thanks.  Here's my implementation:

```javascript
const path = require('path');

// ...

function (bre) {
  const { name: packageName } = require('./package.json');
  const regexp = new RegExp(`\\n?(\\s*)?import\\s*['"](${ packageName }.*)['"]\\s*;`);
  const sourcesPath = bre.config.paths.sources;

  return function (line, fileInfo) {
    if (regexp.test(line)) {
      let capture = regexp.exec(line).pop();

      let relativePath = './' + path.relative(
        path.dirname(fileInfo.absolutePath.replace(sourcesPath, '')),
        capture.replace('@solidstate/contracts', '')
      );

      line = line.replace(capture, relativePath);
    }

    return line;
  };
}
```

**Comment by ItsNickBarry** [comment]
One suggestion that's probably not worth a new release: rename `fileInfo` to `source` or `sourceInfo` to be consistent with the terminology buidler uses.
