### ISSUE TITLE
Imports not processed correctly

### ISSUE THREAD

**Issue by ItsNickBarry** [wighawag/buidler-preprocessor#4]
As mentioned in #2, I've written a preprocessor function which converts imports using the package name to relative paths.  This does not seem to work when an imported contract relies on preprocessing.

For example:

```javascript
// buidler.config.js

// ...

module.exports = {
  preprocess: {
    eachLine: () => (line) => line.replace('PRE', '.'),
  },
};
```

```solidity
// A.sol
import 'PRE/B.sol';
```

```solidity
// B.sol
import 'PRE/C.sol';
```

```solidity
// C.sol
// empty
```

Is this a limitation with Buidler?

**Comment by wighawag** [comment]
I am not sure I get the issue. Do you mean C.sol is not preprocessed ?
if it has no line, it cannot be preprocessed as the preprocessor only act on each line

The way buidler-preprocessor work is it transform all files given by buidler itself, so if for some reason buidler skip some files, then the plugin cannot do much. But looking at buidler TASK_COMPILE_GET_RESOLVED_SOURCES seems to be fine

**Comment by ItsNickBarry** [comment]
No, I mean that the version of `B.sol` imported by `A.sol` is not processed, and compilation fails.

**Comment by wighawag** [comment]
Oh I can actually see why. buidler seems to re-read from file system when dealing with imports. that seems weird to me. Need to investigate more
